name: Test

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}

    - name: Install all dependencies
      run: yarn install

    - name: Run jest
      run: yarn jest